apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-minecraft
bases:
- ../../base
transformers:
- transformer-labels.yaml
- transformer-suffixprefix.yaml
configMapGenerator:
- name: configmap-allowlist-config01
  files:
  - allowlist.json
- name: configmap-permissins-config01
  files:
  - permissions.json
- name: configmap-server-properties-config01
  files:
  - server.properties
images:
  - name: frontend-app01
    newName: abeyuki/minecraft-bedrock-arm64
    newTag: "1.19.2.02"
replicas:
- name: frontend-app01
  count: 1
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: frontend-app01
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn
    volumeMode: Filesystem
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: frontend-app01
    labels:
      app.kubernetes.io: bedrock
  spec:
    type: NodePort
    ports:
      - name: udp
        protocol: UDP
        nodePort: 32767
        port: 19132
        targetPort: 19132
    selector:
      app.kubernetes.io/name: bedrock
