apiVersion: v1
kind: Service
metadata:
  name: frontend-app01
  labels:
    app.kubernetes.io: bedrock
spec:
  type: NodePort
  ports:
    - name: udp
      protocol: UDP
      nodePort: 32767
      port: 19132
      targetPort: 19132
  selector:
    app.kubernetes.io/name: bedrock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-app01
spec:
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-g9-enp4s0-rwx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app01
  labels:
    app.kubernetes.io/name: bedrock
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bedrock
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bedrock
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - bedrock
            topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: init-copy-config
          image: alpine:3.20
          command: ["sh","-c"]
          args:
            - |
              set -eu
              install -m 600 /config/server.properties   /bedrock-server/server.properties
              install -m 600 /secrets/permissions.json   /bedrock-server/permissions.json
              install -m 600 /secrets/allowlist.json     /bedrock-server/allowlist.json
          volumeMounts:
            - name: worlds
              mountPath: /bedrock-server
            - name: projected
              mountPath: /config
              readOnly: true
            - name: permissions-allowlist
              mountPath: /secrets
              readOnly: true
      containers:
      - name: frontend-app01
        image: frontend-app01
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: 3Gi
          limits:
            cpu: "3"
            memory: 5Gi
        env:
        - name: TZ
          value: Asia/Tokyo
        - name: EULA
          value: "true"
        - name: BEDROCK_SERVER_VERSION
          value: "1.21.102.1"
        - name: BOX64_LD_LIBRARY_PATH
          value: "/bedrock-server"
        ports:
        - name: bedrock
          containerPort: 19132
          protocol: UDP
        volumeMounts:
          - name: worlds
            mountPath: /bedrock-server
      volumes:
        - name: worlds
          persistentVolumeClaim:
            claimName: frontend-app01
        - name: projected
          projected:
            sources:
              - configMap:
                  name: server-properties
        - name: permissions-allowlist
          projected:
            sources:
              - secret:
                  name: permissions
              - secret:
                  name: allowlist