apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-minecraft
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: configmap-allowlist-config01
  files:
  - allowlist.json
- name: configmap-permissions-config01
  files:
  - permissions.json
- name: configmap-server-properties-config01
  files:
  - server.properties